name: Test npm package

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-release:
    name: Tagged Release
    runs-on:  ubuntu-20.04    

    steps:
      - name: Checkout source
        uses: actions/checkout@v2        
      
      - name: Install Node      
        uses: actions/setup-node@v1 
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - name: build and test
        working-directory: ./custom-widget-builder
        run: | 
          npm ci
          npm run build
          
      - name: Prepare package
        working-directory: ./custom-widget-builder
        run: npm pack
          